In [1]:
import pandas as pd
import os as os

In [33]:
path_file = os.path.join('C:/yyx/SCH/fourthSeme/fairness/Data/data20190223', 'friend_large.csv')
# path_file = "C:\yyx\SCH\fourthSeme\fairness\Data\data20190223\friend_large.csv"
df = pd.read_csv(path_file, header = None)
df.columns = ['ID1', 'ID2', 'Time']

In [34]:
print(df.head(5))

   ID1    ID2                 Time
0    1     14  2018-06-08 00:00:00
1    1     40  2018-01-03 00:00:00
2    1   5013  2018-06-08 00:00:00
3    1   9436  2018-04-23 00:00:00
4    1  10389  2018-01-03 00:00:00


In [35]:
df2 = df.copy()
print(df2)


                ID1        ID2                 Time
0                 1         14  2018-06-08 00:00:00
1                 1         40  2018-01-03 00:00:00
2                 1       5013  2018-06-08 00:00:00
3                 1       9436  2018-04-23 00:00:00
4                 1      10389  2018-01-03 00:00:00
...             ...        ...                  ...
41703540  218251642  211840761  2019-01-06 12:32:02
41703541  218251642  212736833  2019-01-01 00:00:00
41703542  218251642  212824231  2019-01-01 00:00:00
41703543  218251642  213972518  2019-01-01 00:00:00
41703544  218251642  217079616  2019-01-08 11:51:36

[41703545 rows x 3 columns]


In [36]:
df2 = df2.drop(['Time'],axis=1)

In [37]:
import numpy as np

In [38]:
print(df2.max())

ID1    218251642
ID2    219549211
dtype: int64


In [39]:
df_clear = df2.drop(df2[(df2['ID1']>30000) | (df2['ID2']>30000)].index)

In [40]:
MatFriend = np.zeros(shape=(30000,30000),dtype=int)

In [41]:
print(df_clear)

          ID1    ID2
0           1     14
1           1     40
2           1   5013
3           1   9436
4           1  10389
...       ...    ...
351339  29514  20829
351340  29514  21398
351341  29514  22000
351342  29514  25518
351343  29514  28534

[5777 rows x 2 columns]


In [42]:
for index, ids in df_clear.iterrows():
    id1 =int(ids['ID1'])
    id2 =int(ids['ID2'])
    if id1 <= 30000 and id2 <= 30000:
        MatFriend[id1][id2]=1
        MatFriend[id2][id1]=1
    if id1 != 0:
        MatFriend[id1][id1] = 1
    elif id2 != 0:
        MatFriend[id2][id2] = 1

In [43]:
print(MatFriend)

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [44]:
num = np.count_nonzero(MatFriend)
print(num)

9601


In [45]:
df_final = pd.DataFrame(MatFriend)

In [63]:
print(df_final)

       0      1      2      3      4      5      6      7      8      9      \
0          0      0      0      0      0      0      0      0      0      0   
1          0      1      0      0      0      0      0      0      0      0   
2          0      0      1      0      0      0      0      0      0      0   
3          0      0      0      0      0      0      0      0      0      0   
4          0      0      0      0      0      0      0      0      0      0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
29995      0      0      0      0      0      0      0      0      0      0   
29996      0      0      0      0      0      0      0      0      0      0   
29997      0      0      0      0      0      0      0      0      0      0   
29998      0      0      0      0      0      0      0      0      0      0   
29999      0      0      0      0      0      0      0      0      0      0   

       ...  29990  29991  29992  29993  29994  2999

In [46]:
df_final.to_csv("C:/yyx/SCH/fourthSeme/fairness/Data/data20190223/30000friend_large.csv",header=None)

In [71]:
print(df_final.head(5))

   0      1      2      3      4      5      6      7      8      9      ...  \
0      0      0      0      0      0      0      0      0      0      0  ...   
1      0      1      0      0      0      0      0      0      0      0  ...   
2      0      0      1      0      0      0      0      0      0      0  ...   
3      0      0      0      0      0      0      0      0      0      0  ...   
4      0      0      0      0      0      0      0      0      0      0  ...   

   29990  29991  29992  29993  29994  29995  29996  29997  29998  29999  
0      0      0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0      0      0  

[5 rows x 30000 columns]


In [77]:
'''
outFile = "/Users/yxyang/Desktop/absoluteFairData/data/data20190223/30000friend_large2.txt"
with open(outFile,'w') as fi:

    numObj = numAttr = 30000

    fi.write(str(numObj) + "\n")
    fi.write(str(numAttr) + '\n')

    for i in range(numObj):
        # print(i)
        for j in range(numAttr):
            if i == j:
                MatFriend[i][j] = 1
            fi.write(str(MatFriend[i][j]))
            # fi.write(" ")
        fi.write('\n')
'''

In [47]:
path_file = "C:/yyx/SCH/fourthSeme/fairness/Data/data20190223/user_info.csv"
df3 = pd.read_csv(path_file)

C:\Users\user\AppData\Local\Temp\ipykernel_31548\2325648779.py:2: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv(path_file)


In [48]:
print(df3.head(6))

   id    name realname  gender  mobile birthday  \
0   1      徐俊       徐俊       1     NaN      NaN   
1   2     齐特佳      齐特佳       1     NaN      NaN   
2   7      李晗       李晗       1     NaN      NaN   
3   8      师卉       师卉       2     NaN      NaN   
4  13      张哲       张哲       2     NaN      NaN   
5  14  sherry   sherry       2     NaN      NaN   

                                              avatar company   cmp_id  \
0  http://i9.taou.com/maimai/p/837/973_1_22LolFWs...      脉脉      1.0   
1  http://i9.taou.com/maimai/p/7920/8439_2_81ldVp...      脉脉      1.0   
2  http://i9.taou.com/maimai/p/7159/7341_7_M1GQ4s...    束光文化      0.0   
3  http://i9.taou.com/maimai/p/100/8412_8_hjQ2Eo8...     前脉脉      1.0   
4  http://i9.taou.com/maimai/p/4111/2217_13_11ROd...      搜狗  10182.0   
5  http://i9.taou.com/maimai/p/844/1155_14_5Kx6MM...      脉脉      1.0   

                                             cmp_url  ... work_exp_num  \
0  https://maimai.cn/company?webcid=13DPDwuRC&self=0  ..

In [50]:
df3 = pd.DataFrame(df3,columns=['id','gender'])

In [53]:
print(df3.head(10))

   id  gender
0   1       1
1   2       1
2   7       1
3   8       2
4  13       2
5  14       2
6  15       1
7  16       2
8  17       1
9  22       2


In [59]:
userNewID = {}
for index, ids in df3.iterrows():
    userNewID.update({index: ids[0]})

print(userNewID)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

